# Expected frame id of the ik commands
frame_id: base
# Publish Rate in [Hz]
publish_rate: 500
# Advanced control modes (joint torque or velocity) must be commanded at a rate great than this timeout [seconds]
timeout: 0.02

# Joint Torque controller gains
gains:
#      X trans    Y trans   Z trans   X rot   Y rot   Z rot
  Kp: [150.0,     150.0,    150.0,    5.0,    5.0,    5.0]
  Kd: [20.0,      20.0,     20.0,     1.0,    1.0,    1.0]
