frame_id: base

# joint: [roll, pitch, yaw]
# no_joint when not use
mapping:
  # Left arm
  l_shoulder: [no_joint, no_joint, no_joint]
  l_elbow:    [no_joint, no_joint, no_joint]
  l_wrist:    [no_joint, no_joint, no_joint]
  # Right arm
  r_shoulder: [right_s0, no_joint, no_joint]
  r_elbow:    [no_joint, no_joint, no_joint]
  r_wrist:    [no_joint, no_joint, no_joint]
